### ISSUE TITLE
bot crashes when accented chars are used

### ISSUE THREAD

**Issue by fczuardi** [BotBotMe/botbot-bot#37]
steps to reproduce:

- install bobot following the instructions on http://botbot.readthedocs.org/en/latest/install.html
- run and configure it following the instructions of http://botbot.readthedocs.org/en/latest/getting_started.html
- wait for your bot to join your test channel
- type ```á``` on the chat

expected results:

- the bot logs your message

actual results:

- the bot crashes with this message:

```
Traceback (most recent call last):
  File "/home/botbot/botbot/bin/honcho", line 9, in <module>
    load_entry_point('honcho==0.5.0', 'console_scripts', 'honcho')()
  File "/home/botbot/botbot/local/lib/python2.7/site-packages/honcho/command.py", line 315, in main
    app.parse()
  File "/home/botbot/botbot/local/lib/python2.7/site-packages/honcho/command.py", line 129, in parse
    options.func(self, options)
  File "/home/botbot/botbot/local/lib/python2.7/site-packages/honcho/command.py", line 197, in start
    sys.exit(process_manager.loop())
  File "/home/botbot/botbot/local/lib/python2.7/site-packages/honcho/process.py", line 118, in loop
    print(line, end='', file=proc.printer)
  File "/home/botbot/botbot/local/lib/python2.7/site-packages/honcho/printer.py", line 22, in write
    self.output.write(*new_args, **kwargs)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 182: ordinal not in range(128)
```

My system is Ubuntu 14.10 x64 from DigitalOcean

**Comment by fczuardi** [comment]
maybe related https://github.com/nickstenning/honcho/issues/66

**Comment by fczuardi** [comment]
indeed! adding the following lines to the .env file fixed the issue:

```
LANG=en_US.UTF-8
PYTHONIOENCODING=utf8
```
